### ISSUE TITLE
resize doesn't work on mobile

### ISSUE THREAD

**Issue by lifeiscontent** [table-library/react-table-library#155]
it seems no data table libraries support resize on mobile devices

**Comment by bronglil** [comment]
Since many data tables don’t support resizing on mobile, consider using CSS media queries to adjust widths or create a scrollable layout. For dynamic resizing, add touch event listeners with JavaScript to mimic resizing. Alternatively, libraries like ag-Grid offer partial mobile support, or you can use a stacked card layout for better readability on small screens.

**Comment by lifeiscontent** [comment]
@bronglil thanks for the response, I ended up writing my own implementation, which we might open source at a later time :)

**Comment by bronglil** [comment]
It's great that you developed your own solution! If you choose to open-source it later, it could benefit others facing similar challenges. Feel free to share updates or seek feedback when you're ready.

Thanks
