### ISSUE TITLE
Table doesn't resize correctly with layout={{ custom: true }}

### ISSUE THREAD

**Issue by proddy** [table-library/react-table-library#55]
When re-sizing a window the columns do not automatically adjust when the `custom: true` setting is used.

To reproduce, use the example code below, start with a wide browser window, resize to half it's size and notice the column alignment is wrong and some columns are cut-off. Then F5/Refresh the browser window and see how it correctly adjusts itself during the re-render.

```ts
import { useTheme } from "@table-library/react-table-library/theme";
import {
  Table,
  Header,
  HeaderRow,
  HeaderCell,
  Body,
  Row,
  Cell,
} from "@table-library/react-table-library/table";

import { IconButton } from "@mui/material";
import InfoOutlinedIcon from "@mui/icons-material/InfoOutlined";

const list = [
  {
    id: "1",
    name: "A",
    type: 3,
    code: 10,
  },
  {
    id: "2",
    name: "B",
    type: 2,
    code: 11,
  },
  {
    id: "3",
    name: "C",
    type: 1,
    code: 12,
  },
];

const App = () => {
  const my_theme = useTheme({
    BaseRow: `
      font-size: 14px;
      color: white;
      height: 46px;
      &:focus {
        z-index: 2;
        border-top: 1px solid #177ac9;
        border-bottom: 1px solid #177ac9;
      }
    `,
    HeaderRow: `
      text-transform: uppercase;
      background-color: black;
      color: #90CAF9;
      border-bottom: 1px solid #e0e0e0;
      font-weight: 500;
    `,
    Row: `
      background-color: #1e1e1e;
      border-top: 1px solid #565656;
      border-bottom: 1px solid #565656;
      position: relative;
      z-index: 1;
      &:not(:last-of-type) {
        margin-bottom: -1px;
      }
      &:not(:first-of-type) {
        margin-top: -1px;
      }
      &:hover {
        z-index: 2;
        color: white;
        border-top: 1px solid #177ac9;
        border-bottom: 1px solid #177ac9;
      },
      &.tr.tr-body.row-select.row-select-single-selected, &.tr.tr-body.row-select.row-select-selected {
        background-color: #3d4752;
        color: white;
        font-weight: normal;
        z-index: 2;
        border-top: 1px solid #177ac9;
        border-bottom: 1px solid #177ac9;
      }
    `,
    BaseCell: `
      border-top: 1px solid transparent;
      border-right: 1px solid transparent;
      border-bottom: 1px solid transparent;
      &:not(.stiff) > div {
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
      }
      &:nth-of-type(1) {
        padding-left: 8px;
        min-width: 42px;
        width: 42px;
        div {
          width: 100%;
        }
      }
      &:nth-of-type(2) {
        min-width: 100px;
        width: 100px;
      }
      &:nth-of-type(3) {
        flex: 1;
      }
      &:nth-of-type(4) {
        text-align: center;
        max-width: 100px;
      }
      &:last-of-type {
        padding-left: 0px;
        text-align: center;
        width: 32px;
        min-width: 32px;
        max-width: 32px;
      }
    `,
  });

  return (
    <Table data={{ nodes: list }} theme={my_theme} layout={{ custom: true }}>
      {(tableList) => (
        <>
          <Header>
            <HeaderRow>
              <HeaderCell />
              <HeaderCell resize>NAME</HeaderCell>
              <HeaderCell resize>TYPE</HeaderCell>
              <HeaderCell>CODE</HeaderCell>
              <HeaderCell />
            </HeaderRow>
          </Header>

          <Body>
            {tableList.map((item) => (
              <Row key={item.id} item={item}>
                <Cell>
                  <IconButton size="small">
                    <InfoOutlinedIcon
                      color="info"
                      sx={{ fontSize: 16, verticalAlign: "middle" }}
                    />
                  </IconButton>
                </Cell>
                <Cell>{item.name}</Cell>
                <Cell>{item.type}</Cell>
                <Cell>{item.code}</Cell>
                <Cell>
                  <IconButton size="small">
                    <InfoOutlinedIcon
                      color="info"
                      sx={{ fontSize: 16, verticalAlign: "middle" }}
                    />
                  </IconButton>
                </Cell>
              </Row>
            ))}
          </Body>
        </>
      )}
    </Table>
  );
};

export default App;
```

**Comment by proddy** [comment]
This has been open for almost a month now and I'm still not sure how to fix it by myself. 

Here's a link to the sandbox showing the behaviour when resizing windows: https://codesandbox.io/s/nervous-frost-te7mlh?file=/src/App.tsx

**Comment by rwieruch** [comment]
Hi @proddy It's an issue that we had internally as well, but I had to give it some time and thought about how to solve it. Sorry for not communicating well!

Version `3.2.0-beta.1` should fix this behavior. You can see the fix for your CodeSandbox over here: https://codesandbox.io/s/happy-ully-2v2ce3?file=/src/App.tsx It may be released officially as 3.2.0, but I think 4.0.0 is more likely, because there are breaking changes involved. Please try it yourself and let me know if something is not working properly.

The main things that have changed (some of them you can see in the CodeSandbox too):

- layout via `--data-table-library_grid-template-columns` (everything acceptable what a CSS `grid-template-columns` property would accept) on `Table` property when using `useTheme()`  instead of width/min-width on each `BaseCell`
- table elements (e.g. `table`, `td`, `th`) instead of div elements, but they can be transformed as div elements by using `layout={{ isDiv: true }}`
- less internal styling (padding, margin, etc.), it should be done by individual theming instead

- hide feature: `hideKey: string` became `hide: boolean` on each HeaderCell/Cell, `hiddenColumns` in `layout` not necessary anymore
- fixed header feature: `layout={{ fixedHeader: true }}`
- controlled layout: `layout={{ resizedLayout: string }}` and `layout={{ onLayoutChange: (gridTemplateColumns: string) => void }}` instead of using `string[]`

- new Virtualized component for opt-in virtualization

**Comment by proddy** [comment]
thanks! trying it out now...

**Comment by proddy** [comment]
one question, how would you align text in a column? In my example I was using

```css
     &:nth-of-type(4) {
        text-align: center;
     }
```

**Comment by rwieruch** [comment]
This should be still working, no?

**Comment by proddy** [comment]
> This should be still working, no?

yes it does, sorry!

**Comment by rwieruch** [comment]
@proddy how do you like the new API of just defining the layout with the grid-tempalte-columns?

**Comment by proddy** [comment]
i love it, I'm now busy converting all my tables. I created a common theme and then used that to create styles for all my tables. I reduce the # lines tremendously. thanks!

**Comment by rwieruch** [comment]
v.4.0.0 got released https://github.com/table-library/react-table-library/releases/tag/v4.0.0

**Comment by proddy** [comment]
> v.4.0.0 got released https://github.com/table-library/react-table-library/releases/tag/v4.0.0

I saw, eager to try it out. great work thanks.
